### PR TITLE
Added some improvements

### PR DESCRIPTION
**Pull request by doopz**
* Fix to `fetch_array()` when there are no values
* Correct syntax for an `enum`
* Added more field type mappings
* Removed some unwanted semi colons

### CODE REVIEW

**Comment by doopz** [comment]
@aljorhythm thank you for this script as it helped save me some time when other scripts didn't work. I wanted to contribute some fixes I made to get it to work with my database, in particular `enum`s and `unsigned` values.

There was also a bug fix which was `fetch_array()` was being invoked when `$results` was a `boolean` instead of having records. The fix was to wrap them around the `if` condition like other cases you had already done.

**Comment by aljorhythm** [comment]
thanks @doopz. I have not been maintaining this repo. I wanted to implement some tests and CI/CD here https://github.com/aljorhythm/sql-to-laravel-migrations/pull/12/files, but didn't have time to continue. If you are interested do contribute ideas and code thanks!!

**Comment by aljorhythm** [comment]
unfortunately as i see now your requested changes have conflict @doopz . tests are severely needed hahaha

**Comment by doopz** [comment]
No worries @aljorhythm. I will close this for now as I am not sure when I can get back to this but if I do then I will surely work towards the PR you mentioned instead. Yep, tests are really a life saver in the short and long term.

Anyway thank you for sharing this script which was really helpful to me.

**Comment by aljorhythm** [comment]
no worries glad it helped you. oh man it's alright actually you didn't need to close the PR

**Pull request closed without merging**
